# Generated by Django 2.2 on 2019-05-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=38)),
                ('address', models.CharField(max_length=127)),
                ('contact', models.CharField(max_length=18)),
                ('email_site', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=158)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
