# Generated by Django 2.2 on 2019-05-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law_site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lawyers',
        ),
    ]
